# Oja's Algorithm

## The following cell imports the .db file when run

In [1]:
!ls ../../Data/K_cluster_analysis.db

../../Data/K_cluster_analysis.db


In [2]:
import pandas as pd
import numpy as np
from sklearn import decomposition
from matplotlib import pyplot as plt
import matplotlib.cm as cm
from matplotlib.pyplot import figure
import seaborn as sns
from sklearn.cluster import KMeans
import glob
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [5]:
%%time
#run this to import
try:
    import dill
except:
    %pip install dill
    import dill
dill.load_session('../../Data/K_cluster_analysis.db')
data=data[:,1:]  # remove prefix '1'
data.shape

CPU times: user 193 ms, sys: 557 ms, total: 750 ms
Wall time: 749 ms


(2664671, 12)

### Estimate mean

In [39]:
_mean=np.zeros(data.shape[1])
eta=0.001

In [78]:
means=[]
for i in range(data.shape[0]):
    vector=data[i,:]
    _not_nan=~isnan(vector)
    _newmean=copy(_mean)
    eta=min(0.001,1/(i+5))
    _newmean[_not_nan] = (1-eta)*_mean[_not_nan] + eta*vector[_not_nan]
    if i%100000 == 0:
        print(i,norm(_mean-_newmean))
    _mean=_newmean
    means.append(_mean)

0 0.00012566019948814615
100000 1.4110992926028119e-06
200000 3.4905972016866376e-07
300000 8.250140851538883e-08
400000 5.871203183486922e-08
500000 2.68178602204014e-08
600000 2.0603566478661913e-08
700000 2.1391836749287394e-08
800000 7.250426536890062e-08
900000 3.7425581616697156e-08
1000000 8.996284971454427e-09
1100000 7.060080548045791e-08
1200000 8.926682856046808e-08
1300000 3.008419642461183e-08
1400000 1.2726026401595336e-08
1500000 4.113018819377822e-09
1600000 1.3696279294920792e-08
1700000 3.3121482088380983e-08
1800000 3.441443335115428e-08
1900000 2.61330638025206e-07
2000000 6.250189996893726e-07
2100000 6.339819855212079e-07
2200000 1.9218702177027656e-07
2300000 2.3633721186113327e-08
2400000 3.438447077491205e-08
2500000 5.928961365468249e-07
2600000 6.811701729331191e-08


In [79]:
k=100000
for i in range(0,len(means)-k,k):
    print(i,norm(means[i]-means[i+k]))

0 0.1548606410348017
100000 0.057859927764085405
200000 0.013599378319167093
300000 0.00340521391448316
400000 0.0007516804244264582
500000 0.001927760067769734
600000 0.0014863742468648258
700000 0.0011899874034203104
800000 0.0010206885851345789
900000 0.0034566137399536187
1000000 0.006261872881842813
1100000 0.006080910853215764
1200000 0.003426198973891266
1300000 0.0006581391973207176
1400000 0.0012391753254917858
1500000 0.0003902480206325005
1600000 0.002816652126718424
1700000 0.0057563078591068685
1800000 0.006081149464133909
1900000 0.027835095917031066
2000000 0.021670255936550226
2100000 0.03477641179466254
2200000 0.01831125070150886
2300000 0.002882924121414564
2400000 0.013633169923918439
2500000 0.018726048004889875


In [80]:
norm(means[-1]-means[int(len(means)/2)])

0.11652559986278527

In [81]:
means[10*k]

array([-0.07329919, -0.02682962,  0.9720738 , -0.22365044, -0.04377237,
        0.57023735,  0.00812117,  0.00132767,  0.99941906,  0.10049459,
       -0.02560934,  0.95248385])

In [20]:
eta*vector[_not_nan]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [33]:
_not_nan=~isnan(vector)

In [34]:
_not_nan

array([False, False, False, False, False, False,  True,  True,  True,
       False, False, False])

In [35]:
vector

array([   nan,    nan,    nan,    nan,    nan,    nan, -0.012, -0.   ,
        1.   ,    nan,    nan,    nan])

In [37]:
vector[_not_nan]

array([-0.012, -0.   ,  1.   ])