In [1]:
import pandasToMatrix
import numpy as np
import pickle

### Convert combined .csv files into matrix and pickle dump

In [2]:
list_july_first = pandasToMatrix.main('2020-07-01')

/home/ardelalegre/CSE4223-ODAS/postprocessing/pandasToMatrix.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  temp['X'] = None
/home/ardelalegre/CSE4223-ODAS/postprocessing/pandasToMatrix.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  temp['Y'] = None
/home/ardelalegre/CSE4223-ODAS/postprocessing/pandasToMatrix.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  temp['Z'] = None
/home/ardelalegre/CSE4223-ODAS/postprocessing/pandasToMatrix.py:26: SettingWithCopyWarning: 
A va

In [5]:
july_first_np = list_to_np_arr(list_july_first)

In [6]:
july_first_np[0]

array([-0.444, 0.885, 0.14, None, None, None, None, None, None, None,
       None, None, 1593613233.604519], dtype=object)

In [7]:
# initialize np array as an array of zeros
data = np.zeros((july_first_np.shape[0],13))
print(data.shape)
for (index,i) in enumerate(july_first_np):
    data[index] = np.asarray(july_first_np[index])

(217451, 13)


In [8]:
data[0]

array([-4.44000000e-01,  8.85000000e-01,  1.40000000e-01,             nan,
                   nan,             nan,             nan,             nan,
                   nan,             nan,             nan,             nan,
        1.59361323e+09])

In [ ]:
pickle.dump(july_first_np, open("july_first_np.p", "wb"))

### Load pickle and convert list of lists to np array

In [4]:
def list_to_np_arr(list_form):
    """Converts list of lists into numpy array."""
    data = np.zeros((1,13))
    for i in list_form:
        data = np.append(data,np.asarray(i), axis = 0)
    data = data[1:]
    return data

### Load pickled numpy array and do further type casting

In [2]:
first_july_2020 = pickle.load(open("july_first_np.p", "rb"))

In [5]:
first_july_2020[0]
print(type(first_july_2020[0]))

<class 'numpy.ndarray'>


In [7]:
# # define one row of a np array
# data = np.zeros((1,13))
# print(data.shape)
# for i in first_july_2020:
#     data = np.append(data, np.reshape(np.asarray(i), (1,13)),axis = 0)
# # loop through previous array and convert each element into np array
# # append the resulting np array at each step to the array
# # print(data)


# # this is too slow

(1, 13)


KeyboardInterrupt: 

In [19]:
# initialize np array as an array of zeros
data = np.zeros((first_july_2020.shape[0],13))
print(data.shape)
for (index,i) in enumerate(first_july_2020):
    data[index] = np.asarray(first_july_2020[index])

pickle.dump(data, open("july_first_np.p", "wb"))

(217451, 13)


In [17]:
first_july_2020

array([[-0.444, 0.885, 0.14, ..., None, None, 1593613233.604519],
       [-0.444, 0.885, 0.14, ..., None, None, 1593613233.612516],
       [-0.444, 0.885, 0.14, ..., None, None, 1593613233.6205132],
       ...,
       [-0.649, 0.555, 0.52, ..., None, None, 1593653152.957259],
       [-0.649, 0.555, 0.52, ..., None, None, 1593653152.965256],
       [-0.649, 0.555, 0.52, ..., None, None, 1593653152.973253]],
      dtype=object)

In [18]:
data

array([[-4.44000000e-01,  8.85000000e-01,  1.40000000e-01, ...,
                    nan,             nan,  1.59361323e+09],
       [-4.44000000e-01,  8.85000000e-01,  1.40000000e-01, ...,
                    nan,             nan,  1.59361323e+09],
       [-4.44000000e-01,  8.85000000e-01,  1.40000000e-01, ...,
                    nan,             nan,  1.59361323e+09],
       ...,
       [-6.49000000e-01,  5.55000000e-01,  5.20000000e-01, ...,
                    nan,             nan,  1.59365315e+09],
       [-6.49000000e-01,  5.55000000e-01,  5.20000000e-01, ...,
                    nan,             nan,  1.59365315e+09],
       [-6.49000000e-01,  5.55000000e-01,  5.20000000e-01, ...,
                    nan,             nan,  1.59365315e+09]])

In [ ]:
# converts list of lists into numpy array
data = np.zeros((1,13))
for i in first_july_2020:
    data = np.append(data,np.asarray(i), axis = 0)
data = data[1:]

In [ ]:
print(data.shape)

In [ ]:
# sanity check: is the number of rows in data equal to the total number of entries in all the lists
total_num_entries = 0
for i in first_july_2020:
    total_num_entries = total_num_entries + len(i)
print(total_num_entries)

### Working with datetimes

In [10]:
import datetime
import pickle

In [2]:
datetime.datetime.timestamp()

datetime.datetime(2020, 7, 16, 12, 30, 48, 595400)

In [19]:
format_timestring = '%b %d %Y %I:%M%p'

start_timestring = 'Jul 15 2020 01:40PM'
end_timestring = 'Jul 15 2020 02:00PM'
start_standard_dt_string = datetime.datetime.strptime(start_timestring, format_timestring)
end_standard_dt_string = datetime.datetime.strptime(end_timestring, format_timestring)

print(start_standard_dt_string)
print(datetime.datetime.timestamp(start_standard_dt_string))
print(end_standard_dt_string)
print(datetime.datetime.timestamp(end_standard_dt_string))

2020-07-15 13:40:00
1594845600.0
2020-07-15 14:00:00
1594846800.0


In [14]:
# loading the data from 15th July
data = pickle.load(open('/home/ardelalegre/CSE4223-ODAS/preprocessing/python/exp_15_07.p','rb'))

In [32]:
for x in range(data.shape[0]):
    if(data[x,12] > datetime.datetime.timestamp(start_standard_dt_string) and data[x,12] < datetime.datetime.timestamp(end_standard_dt_string)):
        start_index = x
        break
for y in range(x,data.shape[0]):
    if(data[y,12] > datetime.datetime.timestamp(end_standard_dt_string)):
        end_index = y
        break

In [30]:
start_

datetime.datetime(2020, 7, 15, 13, 40, 4, 87972)

In [34]:
307236*0.008/60

40.9648